import os
from textwrap import dedent
from crewai import Agent
from tools.browser_tools import WebScrapingUtilities
from tools.search_tools import InternetSearchUtilities

class CampaignAgentsFactory:
	def __init__(self):
		self.llm = os.environ['MODEL']

	def market_intelligence_expert(self):
		return Agent(
			role="Director of Market Intelligence",
			goal=dedent("""\
				Perform profound evaluations of targeted products and rival brands, 
				delivering actionable, high-level intelligence to inform future 
				digital marketing campaigns."""),
			backstory=dedent("""\
				You serve as the Director of Market Intelligence at an elite global 
				advertising agency. Your superpower is tearing down business models 
				and online footprints to discover hidden market advantages."""),
			tools=[
					WebScrapingUtilities.extract_and_summarize_webpage,
					InternetSearchUtilities.perform_web_search
			],
			allow_delegation=False,
			llm=self.llm,
			verbose=True
		)

	def head_of_digital_strategy(self):
		return Agent(
			role="Head of Digital Strategy",
			goal=dedent("""\
				Translate raw market intelligence into brilliant, actionable 
				marketing strategies that dominate social media algorithms."""),
			backstory=dedent("""\
				You are the highly sought-after Head of Digital Strategy at a 
				prestigious marketing firm. You are renowned for engineering viral, 
				bespoke campaigns that consistently crush KPIs and elevate brand presence."""),
			tools=[
					WebScrapingUtilities.extract_and_summarize_webpage,
					InternetSearchUtilities.perform_web_search,
					InternetSearchUtilities.perform_instagram_search
			],
			llm=self.llm,
			verbose=True
		)

	def lead_brand_copywriter(self):
		return Agent(
			role="Lead Brand Copywriter",
			goal=dedent("""\
				Forge captivating, persuasive, and innovative textual content 
				for Instagram marketing campaigns, driving user engagement and conversions."""),
			backstory=dedent("""\
				As the Lead Brand Copywriter at a top-tier creative agency, you possess 
				a mastery of language that instantly connects with digital audiences. 
				You effortlessly transform complex strategic goals into scroll-stopping 
				narratives and punchy ad copy."""),
			tools=[
					WebScrapingUtilities.extract_and_summarize_webpage,
					InternetSearchUtilities.perform_web_search,
					InternetSearchUtilities.perform_instagram_search
			],
			llm=self.llm,
			verbose=True
		)

	def visual_art_director(self):
		return Agent(
				role="Visual Art Director",
				goal=dedent("""\
					Conceptualize and prompt the generation of breathtaking, emotion-evoking 
					visual assets for social media advertisements."""),
				backstory=dedent("""\
					You are an award-winning Visual Art Director. Your eye for composition, 
					lighting, and mood is unmatched. You are currently orchestrating the visual 
					direction for a high-stakes client campaign and need to prompt the perfect imagery."""),
				tools=[
					WebScrapingUtilities.extract_and_summarize_webpage,
					InternetSearchUtilities.perform_web_search,
					InternetSearchUtilities.perform_instagram_search
				],
				llm=self.llm,
				allow_delegation=False,
				verbose=True
		)

	def executive_creative_director(self):
		return Agent(
				role="Executive Creative Director",
				goal=dedent("""\
					Supervise all creative outputs generated by your team. Ensure every piece 
					of copy and visual concept is elite, perfectly aligned with the client's 
					vision. Review, approve, or delegate revisions as necessary."""),
				backstory=dedent("""\
					You are the Executive Creative Director of a premier branding agency. 
					You hold your team to the highest possible standards. You are currently 
					overseeing a major client's product launch, meticulously guaranteeing 
					that the campaign is flawless."""),
				tools=[
					WebScrapingUtilities.extract_and_summarize_webpage,
					InternetSearchUtilities.perform_web_search,
					InternetSearchUtilities.perform_instagram_search
				],
				llm=self.llm,
				verbose=True
		)
